changed nvm_node_version
tenantcloud/ansible-role-software-mobile pull request #10
Opened 2020-07-02 14:58 UTC by odebretseni

2020-07-02 15:26 UTC, BrunIF requested changes

2020-07-02 15:26 UTC, BrunIF commented on vars/main.yml
> +nvm_node_version: "v10.21.0"
Я ж писав, що можна писати `v10` і буде остання з цього релізу

2020-07-02 15:57 UTC, odebretseni commented on vars/main.yml
> +nvm_node_version: "v10.21.0"
я знаю і використовую ```node_version: "v10"``` - там всюди так в плейбуках
але при інсталяції він ставить конкретну версію і відповідно будує шляхі по ній - того я і вказую змінну
```nvm_node_version: "v10.21.0"```
до прикладу:
```- name: Create a symbolic link to cordova
  file:
    src: $HOME/.nvm/versions/node/{{ nvm_node_version }}/bin/cordova
    dest: /usr/local/bin/cordova
    state: link```

2020-07-02 18:22 UTC, BrunIF requested changes

2020-07-02 18:22 UTC, BrunIF commented on vars/main.yml
> +nvm_node_version: "v10.21.0"
```bash
nvm version
```

2020-07-02 18:41 UTC, odebretseni commented on vars/main.yml
> +nvm_node_version: "v10.21.0"
дякую

2020-07-03 12:55 UTC, BrunIF approved these changes

2020-07-03 12:55 UTC, merged